x-dev: &dev
  build:
    context: .
    args:
      INSTALL_DEV: "1"
  volumes:
    - .:/srv

services:
  web:
    <<: *dev
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      ENVIRONMENT: development
      SESSION_COOKIE_SECURE: "false"
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    <<: *dev
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      ENVIRONMENT: development
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
      SMTP_TLS: "false"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "127.0.0.1:8025:8025"
